version: '3.8'

services:

  currency-exchange:
    image: azamatsult/currency-converter-currency-exchange-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  currency-conversion:
    image: azamatsult/currency-converter-currency-conversion-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  api-gateway:
    image: azamatsult/currency-converter-api-gateway:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  discovery-server:
    image: azamatsult/currency-converter-discovery-server:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always

networks:
  currency-network: